---
abstract: 'mocks LWP::UserAgent and dispatches your requests/responses'
author:
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130870'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-LWP-Dispatch
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  HTTP::Request: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Test::MockObject: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  homepage: http://github.com/tadam/Test-Mock-LWP-Dispatch
  repository: git://github.com/tadam/Test-Mock-LWP-Dispatch.git
version: 0.06
